# Указываем Netlify, что собирать ничего не нужно — сайт чистый
[build]
  command = ""
  publish = "."

# Полностью отключаем встроенный Netlify Image CDN, который блокируют в РФ
[images]
  remote_images = []